---
version: '3'
services:
  # kafka:
  #   image: landoop/fast-data-dev
  #   ports:
  #     - "2181:2181"
  #     - "3030:3030"
  #     - "3031:3031"
  #     - "9092:9092"
  #     - "8081:8081"
  #     - "8082:8082"
  #     - "8083:8083"
  #   environment:
  #     ADV_HOST: kafka

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  
  magic:
    image: digitsy/kafka-magic
    ports:
      - "8080:80"
    environment:
      KMAGIC_ALLOW_TOPIC_DELETE: "true"
      KMAGIC_ALLOW_SCHEMA_DELETE: "true"